name: datavis-env
channels:
- conda-forge
dependencies:
- python = 3.10
- matplotlib-base
- pandas
- numpy
- scipy
- ipywidgets
- seaborn
- altair>=5.0
- vega_datasets
- jupyterlab>=3.1
- voila>=0.2.11
- ipympl
